name: abc_upi_mobile_scanner
version: 1.0.3
publish_to: https://onepub.dev/api/suosdavuhn/
description: ABC UPI Mobile Scanner Customized Code.
environment: 
  sdk: ^3.1.5
dependencies: 
  js: ^0.6.3
  flutter: 
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter
dev_dependencies: 
  lint: '>=1.10.0 <3.0.0'
  flutter_test: 
    sdk: flutter

flutter: 
  plugin: 
    platforms: 
      android: 
        package: dev.adityabirlacapital.abc_upi_mobile_scanner
        pluginClass: MobileScannerPlugin
      ios: 
        pluginClass: ABCUPIMobileScannerPlugin
      macos: 
        pluginClass: ABCUPIMobileScannerPlugin
      web: 
        pluginClass: ABCUPIMobileScannerWebPlugin
        fileName: abc_upi_mobile_scanner_web_plugin.dart
